#!/bin/bash -e

cd build/
touch fake.o
rm *.o
arm-none-eabi-gcc -c -mcpu=cortex-a9 -mfpu=vfpv3 -mfloat-abi=hard -Wl,-build-id=none -specs=build_files/Xilinx.spec ../$1 ../src/*.c ../src/emulator/*.c -I ../src/ -I ../include/external -I../src/emulator -std=c11 -Wall -Werror -g
cd ../
arm-none-eabi-gcc -mcpu=cortex-a9 -mfpu=vfpv3 -mfloat-abi=hard -Wl,-build-id=none -specs=build/build_files/Xilinx.spec -Wl,-T -Wl,build/build_files/lscript.ld build/*.o build/emulator/*.o -o build/app.elf -Wl,--start-group,-lxil,-llwip4,-lgcc,-lc,--end-group -Llib/ -Wl,-Map=build/app.map -g
arm-none-eabi-objdump -d -S build/app.elf > build/app.diss

bin/qemu-system-aarch64 -M xilinx-zynq-a9 -m 1024 -serial /dev/null -serial mon:stdio -display none -kernel build/app.elf -s
