#!/bin/bash

arm-none-eabi-gcc -mcpu=cortex-a9 -mfpu=vfpv3 -mfloat-abi=hard -Wl,-build-id=none -specs=build/build_files/Xilinx.spec -Wl,-T -Wl,build/build_files/lscript.ld $1 src/global_timer.c src/system.c src/time_util.c src/uart.c -I src/ -o build/app.elf -Wl,--start-group,-lxil,-lgcc,-lc,--end-group -Llib/ -Wl,-Map=build/app.map
bootgen -image build/build_files/application.bif -o build/BOOT.bin -w
