#!/bin/bash -e

cd build/
touch fake.o
rm *.o
build="`date +%Y-%M-%d` `git rev-parse HEAD`"
arm-none-eabi-gcc -DFIRMWARE_REVISION=\""$build"\" -c -mcpu=cortex-a9 -mfpu=vfpv3 -mfloat-abi=hard -Wl,-build-id=none -specs=build_files/Xilinx.spec ../$1 ../src/*.c ../src/hardware/*.c -I ../src/ -I ../bit -I ../include/xilinx -I../src/hardware -std=c11 -Wall -Werror -g
cd ../
arm-none-eabi-gcc -DFIRMWARE_REVISION=\""$build"\" -mcpu=cortex-a9 -mfpu=vfpv3 -mfloat-abi=hard -Wl,-build-id=none -specs=build/build_files/Xilinx.spec -Wl,-T -Wl,build/build_files/lscript.ld build/*.o -o build/app.elf -Wl,--start-group,-lxil,-llwip4,-lgcc,-lc,-lm,--end-group -Llib/ -Wl,-Map=build/app.map -g
arm-none-eabi-objdump -d -S build/app.elf > build/app.diss

if [[ $# -eq 2 ]];
then
    cat <<EOF > build/build_files/application.bif
//arch = zynq; split = false; format = BIN
the_ROM_image:
{
[bootloader]./bin/fsbl.elf
$2
./build/app.elf
}
EOF

    bootgen -image build/build_files/application.bif -o build/BOOT.bin -w
fi
